- hosts: web
  remote_user: root
  become: yes
  tasks:
  - name: Install apache
    yum:
      name: httpd
      state: installed
  - name: Restart apache
    yum:
      name: service
      state: restart
